"""
Testi dell'impalcatura del catalogo in ogni lingua: nomi delle macro-categorie, prosa del markdown,
etichette di stato e interfaccia della pagina web.

I *dati* (cosa fa, quando usarlo) non stanno qui: si scrivono in italiano in github-repos.json e
siti-web.json, e le loro traduzioni in traduzioni/<lingua>.json (vedi traduzioni.py).
Per aggiungere una lingua: una voce qui con le stesse chiavi di 'it', e la lingua in
traduzioni.LINGUE.
"""

LOCALI = {
 'it': {
  'nome': 'Italiano',
  'titolo': 'Catalogo strumenti AI & Dev',
  'fonte': 'reel e link salvati in chat',
  'macro': {
   'A': 'Coding Agent, Claude Code & sviluppo AI-assistito',
   'B': 'Framework Agenti AI & assistenti personali',
   'C': 'LLM, modelli & inferenza locale',
   'D': 'RAG, memoria agenti & knowledge base',
   'E': 'OCR & parsing documenti',
   'F': 'Generazione media (video, immagini, 3D, voce)',
   'G': 'Sicurezza & supply-chain',
   'H': 'Dev tools, produttività & librerie',
   'I': 'Finanza & trading AI',
   'J': 'Ricerca AI, world models & dati vettoriali',
   'Z': 'Contenuti personali / non-dev',
  },
  # nella barra dei filtri della pagina web i nomi interi andrebbero a capo
  'macro_breve': {
   'A': 'Coding agent & Claude Code', 'B': 'Framework agenti AI', 'C': 'LLM & inferenza locale',
   'D': 'RAG & memoria', 'E': 'OCR & documenti', 'F': 'Generazione media', 'G': 'Sicurezza',
   'H': 'Dev tools', 'I': 'Finanza & trading', 'J': 'Ricerca AI',
  },
  'stato': {'archiviato': 'archiviato', 'nd': 'n/d', 'molto_attivo': 'molto attivo',
            'attivo': 'attivo', 'rallentato': 'rallentato', 'fermo': 'fermo',
            'sito': 'sito web'},
  'intro':   '> Catalogo unificato di **repository GitHub** e **siti/servizi web** raccolti dai',
  'conteggi': '> **{r} repository** + **{s} siti web**, organizzati per categoria operativa.',
  'verifica': '> Stato attività verificato il **{d}**. ',
  'legenda': 'Legenda: 🟢 attivo (push ≤12 mesi) · 🟡 rallentato · 🔴 fermo · ⚫ archiviato · 🌐 sito web.',
  'indice':  '## Indice',
  'header':  '| Progetto | Cosa fa | Quando usarlo | Stato |',
  'cella_sito': '🌐 sito',
  'z_nota': 'voci non rilevanti per i progetti (salute, ricette, social) — ignorabili.',
  'piede_pub': 'Catalogo pubblicato: raccolta personale, non esaustiva.',
  'piede_skill': 'Copia installata con la skill: comprende anche le voci aggiunte da te, '
                 'segnalate come tali.',
  'ui': {
   'cerca_ph': 'Cerca per nome, cosa fa, quando usarlo…', 'cerca_aria': 'Cerca nel catalogo',
   'ordina': 'Ordina', 'ord_stelle': 'Più stelle', 'ord_push': 'Aggiornati di recente',
   'ord_nome': 'Nome A–Z', 'filtri': 'Filtri', 'leg_cat': 'Categoria', 'leg_att': 'Attività',
   'leg_lic': 'Licenza', 'lingua': 'Lingua',
   'lic': {'libera': 'Libera', 'copyleft': 'Copyleft (GPL/AGPL)',
           'limitata': 'Non commerciale / limitata', 'chiusa': 'Non riusabile',
           'ignota': 'Da verificare', 'sito': 'Siti web'},
   'conteggio': '{n} voci su {t}', 'azzera': 'Azzera filtri',
   'vuoto': 'Nessuna voce corrisponde. Prova a togliere un filtro.',
   'quando': 'Quando usarlo — ', 'lic_ignota': 'licenza da verificare',
   'voce_tua': 'voce tua', 'modificata': 'modificata da te',
   'originale': 'testo originale in italiano',
   'repository': 'repository', 'siti': 'siti web', 'categorie': 'categorie',
   'verificata': 'attività verificata il',
   'piede_licenze': 'Le licenze dei progetti elencati sono quelle dei rispettivi autori. '
                    'Stelle e date vengono da GitHub.',
  },
 },
 'en': {
  'nome': 'English',
  'titolo': 'AI & Dev tools catalog',
  'fonte': 'reels and links saved in chat',
  'macro': {
   'A': 'Coding agents, Claude Code & AI-assisted development',
   'B': 'AI agent frameworks & personal assistants',
   'C': 'LLMs, models & local inference',
   'D': 'RAG, agent memory & knowledge bases',
   'E': 'OCR & document parsing',
   'F': 'Media generation (video, images, 3D, voice)',
   'G': 'Security & supply chain',
   'H': 'Dev tools, productivity & libraries',
   'I': 'AI finance & trading',
   'J': 'AI research, world models & vector data',
   'Z': 'Personal / non-dev content',
  },
  'macro_breve': {
   'A': 'Coding agents & Claude Code', 'B': 'AI agent frameworks', 'C': 'LLMs & local inference',
   'D': 'RAG & memory', 'E': 'OCR & documents', 'F': 'Media generation', 'G': 'Security',
   'H': 'Dev tools', 'I': 'Finance & trading', 'J': 'AI research',
  },
  'stato': {'archiviato': 'archived', 'nd': 'n/a', 'molto_attivo': 'very active',
            'attivo': 'active', 'rallentato': 'slowing down', 'fermo': 'stalled',
            'sito': 'website'},
  'intro':   '> A unified catalog of **GitHub repositories** and **websites/services** collected from',
  'conteggi': '> **{r} repositories** + **{s} websites**, grouped by practical category.',
  'verifica': '> Activity status checked on **{d}**. ',
  'legenda': 'Legend: 🟢 active (pushed ≤12 months ago) · 🟡 slowing down · 🔴 stalled · ⚫ archived · 🌐 website.',
  'indice':  '## Index',
  'header':  '| Project | What it does | When to use it | Status |',
  'cella_sito': '🌐 site',
  'z_nota': 'entries not relevant to dev work (health, recipes, social) — safe to ignore.',
  'piede_pub': 'Published catalog: a personal collection, not an exhaustive one.',
  'piede_skill': 'Copy installed with the skill: it also includes the entries you added, '
                 'marked as such.',
  'ui': {
   'cerca_ph': 'Search by name, what it does, when to use it…', 'cerca_aria': 'Search the catalog',
   'ordina': 'Sort', 'ord_stelle': 'Most stars', 'ord_push': 'Recently updated',
   'ord_nome': 'Name A–Z', 'filtri': 'Filters', 'leg_cat': 'Category', 'leg_att': 'Activity',
   'leg_lic': 'License', 'lingua': 'Language',
   'lic': {'libera': 'Permissive', 'copyleft': 'Copyleft (GPL/AGPL)',
           'limitata': 'Non-commercial / restricted', 'chiusa': 'Not reusable',
           'ignota': 'To be checked', 'sito': 'Websites'},
   'conteggio': '{n} of {t} entries', 'azzera': 'Clear filters',
   'vuoto': 'No entries match. Try removing a filter.',
   'quando': 'When to use it — ', 'lic_ignota': 'license to be checked',
   'voce_tua': 'your entry', 'modificata': 'edited by you',
   'originale': 'original text in Italian',
   'repository': 'repositories', 'siti': 'websites', 'categorie': 'categories',
   'verificata': 'activity checked on',
   'piede_licenze': 'The licenses of the listed projects are those of their authors. '
                    'Stars and dates come from GitHub.',
  },
 },
 'es': {
  'nome': 'Español',
  'titolo': 'Catálogo de herramientas de IA y desarrollo',
  'fonte': 'reels y enlaces guardados en el chat',
  'macro': {
   'A': 'Agentes de código, Claude Code y desarrollo asistido por IA',
   'B': 'Frameworks de agentes de IA y asistentes personales',
   'C': 'LLM, modelos e inferencia local',
   'D': 'RAG, memoria de agentes y bases de conocimiento',
   'E': 'OCR y análisis de documentos',
   'F': 'Generación multimedia (vídeo, imágenes, 3D, voz)',
   'G': 'Seguridad y cadena de suministro',
   'H': 'Herramientas de desarrollo, productividad y librerías',
   'I': 'Finanzas y trading con IA',
   'J': 'Investigación en IA, world models y datos vectoriales',
   'Z': 'Contenido personal / ajeno al desarrollo',
  },
  'macro_breve': {
   'A': 'Agentes de código y Claude Code', 'B': 'Frameworks de agentes IA',
   'C': 'LLM e inferencia local', 'D': 'RAG y memoria', 'E': 'OCR y documentos',
   'F': 'Generación multimedia', 'G': 'Seguridad', 'H': 'Herramientas dev',
   'I': 'Finanzas y trading', 'J': 'Investigación IA',
  },
  'stato': {'archiviato': 'archivado', 'nd': 'n/d', 'molto_attivo': 'muy activo',
            'attivo': 'activo', 'rallentato': 'ralentizado', 'fermo': 'detenido',
            'sito': 'sitio web'},
  'intro':   '> Catálogo unificado de **repositorios de GitHub** y **sitios/servicios web** recopilados de',
  'conteggi': '> **{r} repositorios** + **{s} sitios web**, organizados por categoría práctica.',
  'verifica': '> Estado de actividad comprobado el **{d}**. ',
  'legenda': 'Leyenda: 🟢 activo (push ≤12 meses) · 🟡 ralentizado · 🔴 detenido · ⚫ archivado · 🌐 sitio web.',
  'indice':  '## Índice',
  'header':  '| Proyecto | Qué hace | Cuándo usarlo | Estado |',
  'cella_sito': '🌐 sitio',
  'z_nota': 'entradas ajenas al desarrollo (salud, recetas, redes sociales): se pueden ignorar.',
  'piede_pub': 'Catálogo publicado: una colección personal, no exhaustiva.',
  'piede_skill': 'Copia instalada con la skill: incluye también las entradas que añadiste, '
                 'marcadas como tales.',
  'ui': {
   'cerca_ph': 'Buscar por nombre, qué hace, cuándo usarlo…', 'cerca_aria': 'Buscar en el catálogo',
   'ordina': 'Ordenar', 'ord_stelle': 'Más estrellas', 'ord_push': 'Actualizados recientemente',
   'ord_nome': 'Nombre A–Z', 'filtri': 'Filtros', 'leg_cat': 'Categoría', 'leg_att': 'Actividad',
   'leg_lic': 'Licencia', 'lingua': 'Idioma',
   'lic': {'libera': 'Libre', 'copyleft': 'Copyleft (GPL/AGPL)',
           'limitata': 'No comercial / restringida', 'chiusa': 'No reutilizable',
           'ignota': 'Por verificar', 'sito': 'Sitios web'},
   'conteggio': '{n} de {t} entradas', 'azzera': 'Quitar filtros',
   'vuoto': 'Ninguna entrada coincide. Prueba a quitar un filtro.',
   'quando': 'Cuándo usarlo — ', 'lic_ignota': 'licencia por verificar',
   'voce_tua': 'entrada tuya', 'modificata': 'modificada por ti',
   'originale': 'texto original en italiano',
   'repository': 'repositorios', 'siti': 'sitios web', 'categorie': 'categorías',
   'verificata': 'actividad comprobada el',
   'piede_licenze': 'Las licencias de los proyectos listados son las de sus autores. '
                    'Las estrellas y las fechas provienen de GitHub.',
  },
 },
 'de': {
  'nome': 'Deutsch',
  'titolo': 'Katalog von KI- & Dev-Tools',
  'fonte': 'Reels und im Chat gespeicherte Links',
  'macro': {
   'A': 'Coding-Agents, Claude Code & KI-gestützte Entwicklung',
   'B': 'KI-Agenten-Frameworks & persönliche Assistenten',
   'C': 'LLMs, Modelle & lokale Inferenz',
   'D': 'RAG, Agenten-Gedächtnis & Wissensdatenbanken',
   'E': 'OCR & Dokumentenanalyse',
   'F': 'Mediengenerierung (Video, Bilder, 3D, Stimme)',
   'G': 'Sicherheit & Lieferkette',
   'H': 'Entwicklerwerkzeuge, Produktivität & Bibliotheken',
   'I': 'KI für Finanzen & Trading',
   'J': 'KI-Forschung, World Models & Vektordaten',
   'Z': 'Persönliche Inhalte / nicht entwicklungsbezogen',
  },
  'macro_breve': {
   'A': 'Coding-Agents & Claude Code', 'B': 'KI-Agenten-Frameworks',
   'C': 'LLMs & lokale Inferenz', 'D': 'RAG & Gedächtnis', 'E': 'OCR & Dokumente',
   'F': 'Mediengenerierung', 'G': 'Sicherheit', 'H': 'Dev-Tools',
   'I': 'Finanzen & Trading', 'J': 'KI-Forschung',
  },
  'stato': {'archiviato': 'archiviert', 'nd': 'k. A.', 'molto_attivo': 'sehr aktiv',
            'attivo': 'aktiv', 'rallentato': 'verlangsamt', 'fermo': 'inaktiv',
            'sito': 'Website'},
  'intro':   '> Ein einheitlicher Katalog von **GitHub-Repositories** und **Websites/Diensten**, gesammelt aus',
  'conteggi': '> **{r} Repositories** + **{s} Websites**, nach praktischer Kategorie geordnet.',
  'verifica': '> Aktivitätsstatus geprüft am **{d}**. ',
  'legenda': 'Legende: 🟢 aktiv (Push ≤12 Monate) · 🟡 verlangsamt · 🔴 inaktiv · ⚫ archiviert · 🌐 Website.',
  'indice':  '## Inhalt',
  'header':  '| Projekt | Was es tut | Wann einsetzen | Status |',
  'cella_sito': '🌐 Website',
  'z_nota': 'für die Entwicklung nicht relevante Einträge (Gesundheit, Rezepte, soziale Medien) – ignorierbar.',
  'piede_pub': 'Veröffentlichter Katalog: eine persönliche, nicht vollständige Sammlung.',
  'piede_skill': 'Mit dem Skill installierte Kopie: enthält auch deine eigenen Einträge, '
                 'als solche gekennzeichnet.',
  'ui': {
   'cerca_ph': 'Suche nach Name, Funktion, Einsatzzweck…', 'cerca_aria': 'Katalog durchsuchen',
   'ordina': 'Sortieren', 'ord_stelle': 'Meiste Sterne', 'ord_push': 'Kürzlich aktualisiert',
   'ord_nome': 'Name A–Z', 'filtri': 'Filter', 'leg_cat': 'Kategorie', 'leg_att': 'Aktivität',
   'leg_lic': 'Lizenz', 'lingua': 'Sprache',
   'lic': {'libera': 'Frei', 'copyleft': 'Copyleft (GPL/AGPL)',
           'limitata': 'Nicht kommerziell / eingeschränkt', 'chiusa': 'Nicht wiederverwendbar',
           'ignota': 'Zu prüfen', 'sito': 'Websites'},
   'conteggio': '{n} von {t} Einträgen', 'azzera': 'Filter zurücksetzen',
   'vuoto': 'Kein Eintrag passt. Entferne einen Filter.',
   'quando': 'Wann einsetzen — ', 'lic_ignota': 'Lizenz zu prüfen',
   'voce_tua': 'dein Eintrag', 'modificata': 'von dir geändert',
   'originale': 'Originaltext auf Italienisch',
   'repository': 'Repositories', 'siti': 'Websites', 'categorie': 'Kategorien',
   'verificata': 'Aktivität geprüft am',
   'piede_licenze': 'Die Lizenzen der aufgeführten Projekte sind die ihrer Autoren. '
                    'Sterne und Daten stammen von GitHub.',
  },
 },
 'fr': {
  'nome': 'Français',
  'titolo': 'Catalogue d’outils IA & dev',
  'fonte': 'reels et liens enregistrés dans le chat',
  'macro': {
   'A': 'Agents de code, Claude Code & développement assisté par IA',
   'B': 'Frameworks d’agents IA & assistants personnels',
   'C': 'LLM, modèles & inférence locale',
   'D': 'RAG, mémoire d’agents & bases de connaissances',
   'E': 'OCR & analyse de documents',
   'F': 'Génération de médias (vidéo, images, 3D, voix)',
   'G': 'Sécurité & chaîne d’approvisionnement',
   'H': 'Outils de développement, productivité & bibliothèques',
   'I': 'IA pour la finance & le trading',
   'J': 'Recherche en IA, world models & données vectorielles',
   'Z': 'Contenus personnels / hors développement',
  },
  'macro_breve': {
   'A': 'Agents de code & Claude Code', 'B': 'Frameworks d’agents IA',
   'C': 'LLM & inférence locale', 'D': 'RAG & mémoire', 'E': 'OCR & documents',
   'F': 'Génération de médias', 'G': 'Sécurité', 'H': 'Outils dev',
   'I': 'Finance & trading', 'J': 'Recherche IA',
  },
  'stato': {'archiviato': 'archivé', 'nd': 'n/d', 'molto_attivo': 'très actif',
            'attivo': 'actif', 'rallentato': 'ralenti', 'fermo': 'à l’arrêt',
            'sito': 'site web'},
  'intro':   '> Catalogue unifié de **dépôts GitHub** et de **sites/services web** collectés à partir de',
  'conteggi': '> **{r} dépôts** + **{s} sites web**, classés par catégorie pratique.',
  'verifica': '> État d’activité vérifié le **{d}**. ',
  'legenda': 'Légende : 🟢 actif (push ≤ 12 mois) · 🟡 ralenti · 🔴 à l’arrêt · ⚫ archivé · 🌐 site web.',
  'indice':  '## Sommaire',
  'header':  '| Projet | Ce qu’il fait | Quand l’utiliser | État |',
  'cella_sito': '🌐 site',
  'z_nota': 'entrées sans rapport avec le développement (santé, recettes, réseaux sociaux) : à ignorer.',
  'piede_pub': 'Catalogue publié : une collection personnelle, non exhaustive.',
  'piede_skill': 'Copie installée avec la skill : elle comprend aussi les entrées que vous avez '
                 'ajoutées, signalées comme telles.',
  'ui': {
   'cerca_ph': 'Rechercher par nom, fonction, cas d’usage…',
   'cerca_aria': 'Rechercher dans le catalogue',
   'ordina': 'Trier', 'ord_stelle': 'Plus d’étoiles', 'ord_push': 'Mis à jour récemment',
   'ord_nome': 'Nom A–Z', 'filtri': 'Filtres', 'leg_cat': 'Catégorie', 'leg_att': 'Activité',
   'leg_lic': 'Licence', 'lingua': 'Langue',
   'lic': {'libera': 'Libre', 'copyleft': 'Copyleft (GPL/AGPL)',
           'limitata': 'Non commerciale / restreinte', 'chiusa': 'Non réutilisable',
           'ignota': 'À vérifier', 'sito': 'Sites web'},
   'conteggio': '{n} entrées sur {t}', 'azzera': 'Effacer les filtres',
   'vuoto': 'Aucune entrée ne correspond. Essayez de retirer un filtre.',
   'quando': 'Quand l’utiliser — ', 'lic_ignota': 'licence à vérifier',
   'voce_tua': 'votre entrée', 'modificata': 'modifiée par vous',
   'originale': 'texte original en italien',
   'repository': 'dépôts', 'siti': 'sites web', 'categorie': 'catégories',
   'verificata': 'activité vérifiée le',
   'piede_licenze': 'Les licences des projets listés sont celles de leurs auteurs. '
                    'Les étoiles et les dates proviennent de GitHub.',
  },
 },
}
